project_identifier: craft-docs
api_key_env: CROWDIN_API_KEY
base_path: /
preserve_hierarchy: true
files:
  - source: '**.md'
    ignore:
      - /ja/
    translation: /%two_letters_code%/%original_path%/%file_name%.md
    type: md
